/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class KlockClient {
  constructor()
  /** Register an agent with a priority (lower = older = higher priority). */
  registerAgent(agentId: string, priority: number): void
  /**
   * Acquire a lease on a resource.
   * Returns a JSON string with the result.
   */
  acquireLease(agentId: string, sessionId: string, resourceType: string, resourcePath: string, predicate: string, ttl: number): string
  /** Release a lease by ID. */
  releaseLease(leaseId: string): boolean
  /** Get count of active leases. */
  activeLeaseCount(): number
  /** Evict expired leases. Returns number evicted. */
  evictExpired(): number
}
