/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class KlockClient {
  constructor()
  /** Register an agent with a priority (lower = older = higher priority). */
  registerAgent(agentId: string, priority: number): void
  /**
   * Acquire a lease on a resource.
   * Returns a JSON string with the result.
   */
  acquireLease(agentId: string, sessionId: string, resourceType: string, resourcePath: string, predicate: string, ttl: number): string
  /** Release a lease by ID. */
  releaseLease(leaseId: string): boolean
  /** Get count of active leases. */
  activeLeaseCount(): number
  /** Evict expired leases. Returns number evicted. */
  evictExpired(): number
}

export interface KlockHttpClientOptions {
  baseUrl?: string
  apiKey?: string
  timeoutMs?: number
  autoStart?: boolean
  startupTimeoutMs?: number
  serverCommand?: string[]
}

export interface HttpLeaseResult {
  success: boolean
  leaseId?: string
  agentId?: string
  resource?: string
  predicate?: string
  expiresAt?: number
  reason?: string
  waitTime?: number
}

export interface ActiveLeaseInfo {
  id: string
  agentId: string
  resource: string
  predicate: string
  expiresAt: number
}

export declare class KlockHttpClient {
  constructor(options?: KlockHttpClientOptions)
  autoStart: boolean
  autoStartDisabledByEnv: boolean
  autoStartAttempted: boolean
  autoStartedPid: number | null
  registerAgent(agentId: string, priority: number): Promise<void>
  acquireLease(agentId: string, sessionId: string, resourceType: string, resourcePath: string, predicate: string, ttl: number): Promise<HttpLeaseResult>
  releaseLease(leaseId: string): Promise<boolean>
  heartbeatLease(leaseId: string): Promise<boolean>
  listLeases(): Promise<ActiveLeaseInfo[]>
}
