/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class KlockClient {
  constructor()
  /** Register an agent with a priority (lower = older = higher priority). */
  registerAgent(agentId: string, priority: number): void
  /**
   * Acquire a lease on a resource.
   * Returns a JSON string with the result.
   */
  acquireLease(agentId: string, sessionId: string, resourceType: string, resourcePath: string, predicate: string, ttl: number): string
  /** Release a lease by ID. */
  releaseLease(leaseId: string): boolean
  /** Get count of active leases. */
  activeLeaseCount(): number
  /** Evict expired leases. Returns number evicted. */
  evictExpired(): number
}

// === klock-http-client.d.ts (appended by postbuild) ===
/*
 * Hand-maintained TypeScript declarations for the JS-only KlockHttpClient.
 *
 * This file is concatenated onto NAPI-RS's auto-generated `index.d.ts` by
 * the `postbuild` script. Do NOT edit `index.d.ts` directly — NAPI rewrites
 * it on every build.
 */

/** Constructor options for the HTTP-backed client. */
export interface KlockHttpClientOptions {
  /** Base URL of the Klock server. Defaults to "http://localhost:3100". */
  baseUrl?: string
  /** Bearer token for the `Authorization` header. Optional. */
  apiKey?: string | null
  /** Per-request timeout in milliseconds. Defaults to 5000. */
  timeoutMs?: number
  /** Auto-start a local server when the URL is localhost and the server is unreachable. Defaults to true. */
  autoStart?: boolean
  /** Total startup timeout for auto-start, in milliseconds. Defaults to 5000. */
  startupTimeoutMs?: number
  /** Command + args used to spawn the local server. Defaults to a sane built-in. */
  serverCommand?: readonly string[]
}

export type KlockResourceType =
  | 'FILE'
  | 'SYMBOL'
  | 'API_ENDPOINT'
  | 'DATABASE_TABLE'
  | 'CONFIG_KEY'
  | (string & {})

export type KlockPredicate =
  | 'PROVIDES'
  | 'CONSUMES'
  | 'MUTATES'
  | 'DELETES'
  | 'DEPENDS_ON'
  | 'RENAMES'
  | (string & {})

export type KlockFailureReason =
  | 'WAIT'
  | 'DIE'
  | 'CONFLICT'
  | 'RESOURCE_LOCKED'
  | 'SESSION_EXPIRED'
  | 'STORAGE_UNAVAILABLE'
  | (string & {})

export interface AcquireLeaseSuccess {
  success: true
  leaseId: string
  agentId: string
  resource: string
  predicate: KlockPredicate
  expiresAt: number
}

export interface AcquireLeaseFailure {
  success: false
  reason: KlockFailureReason
  waitTime: number
}

export type AcquireLeaseResult = AcquireLeaseSuccess | AcquireLeaseFailure

export interface ActiveLeaseInfo {
  id: string
  agentId: string
  resource: string
  predicate: KlockPredicate
  expiresAt: number
}

/**
 * HTTP-backed client for a local or remote Klock coordination server.
 * Uses the same wire protocol as the Python `KlockHttpClient`.
 */
export declare class KlockHttpClient {
  constructor(options?: KlockHttpClientOptions)
  /** Register an agent priority on the server. Lower = older = higher priority. */
  registerAgent(agentId: string, priority: number): Promise<void>
  /** Acquire a lease. Resolves to either a success or a typed failure (no throw on conflict). */
  acquireLease(
    agentId: string,
    sessionId: string,
    resourceType: KlockResourceType,
    resourcePath: string,
    predicate: KlockPredicate,
    ttl: number,
  ): Promise<AcquireLeaseResult>
  /** Release a held lease. Returns true if the server reported success. */
  releaseLease(leaseId: string): Promise<boolean>
  /** Refresh a held lease's TTL. */
  heartbeatLease(leaseId: string): Promise<boolean>
  /** List all currently active leases. */
  listLeases(): Promise<ActiveLeaseInfo[]>
}

// === klock-facade.d.ts (appended by postbuild) ===
export type KlockFileMode =
  | 'read'
  | 'mutate'
  | 'delete'
  | 'rename'
  | 'provide'
  | 'depend'

export interface KlockLocalOptions {
  agentId?: string
  sessionId?: string
  priority?: number
  baseUrl?: string
  apiKey?: string | null
  timeoutMs?: number
  autoStart?: boolean
  startupTimeoutMs?: number
  serverCommand?: readonly string[]
}

export interface KlockEmbeddedOptions {
  agentId?: string
  sessionId?: string
  priority?: number
}

export interface KlockFileOptions {
  mode?: KlockFileMode
  ttlMs?: number
  maxRetries?: number
}

export declare class Klock {
  static local(options?: KlockLocalOptions): Klock
  static embedded(options?: KlockEmbeddedOptions): Klock
  registerAgent(agentId: string, priority: number): Promise<void>
  acquireLease(
    agentId: string,
    sessionId: string,
    resourceType: string,
    resourcePath: string,
    predicate: string,
    ttl: number,
  ): Promise<AcquireLeaseResult>
  releaseLease(leaseId: string): Promise<boolean>
  withFile<T>(
    path: string,
    options: KlockFileOptions,
    callback: () => T | Promise<T>,
  ): Promise<T>
  withFile<T>(path: string, callback: () => T | Promise<T>): Promise<T>
}
